### PR TITLE
improve error messages when specifying invalid arguments

### PR DESCRIPTION
**Pull request by arvidn**
Don't keep running when doing so. How do we feel about c++14? Specifically user defined literals for strings.

### CODE REVIEW

**Comment by ssiloti** [comment]
The Bittorrent bootstrap servers are using gcc 4.8 which doesn't support C++14. I can ask IT to upgrade them, but I suspect it will be rather low priority for them.

**Comment by arvidn** [comment]
ah.. the last version to not support them :/ Ok, I'll update this

**Comment by arvidn** [comment]
I've confirmed that this is supported by GCC 4.8.1 here:

http://gcc.godbolt.org/#compilers:!((compiler:g481,options:'-O3+-std%3Dc%2B%2B11',source:'%23include+%3Cstring%3E%0A+%0Astd::string+operator+%22%22+_s(const+char*+str,+size_t+len)%0A%7B+return+std::string(str,+len)%3B+%7D%0A%0Aint+main()%0A%7B%0A++char+const*+literal+%3D+%22foo%22%3B%0A++%0A++if+(literal+%3D%3D+%22foo%22_s)+%7B%0A++++printf(%22yes%5Cn%22)%3B%0A++%7D+else+%7B%0A++++printf(%22no%5Cn%22)%3B%0A++%7D%0A%7D%0A')),filterAsm:(commentOnly:!t,directives:!t,labels:!t),version:3

**Comment by ssiloti** [comment]
lgtm

**Pull request merged**
