### PR TITLE
separate IPv4 and IPv6 backup stats

### PR DESCRIPTION
**Pull request by arvidn**
I'm seeing a lot of returning of backup nodes, my theory is that the v6 table is very small/empty. Also make the get_nodes wrapper honor the requested_nodes argument

### CODE REVIEW

**Comment by arvidn** [comment]
travis: https://travis-ci.org/arvidn/bootstrap-dht/builds/160831021

**Review by ssiloti — APPROVED** [review]
please rebase

**Comment by arvidn** [comment]
@ssiloti rebased

**Comment by ValZapod** [comment]
It is not small anymore? right?

**Pull request merged**
